# 服务
server:
  host: "localhost"
  port: 8080
# 应用
application:
  name: "CarefulAdmin 后台管理"
  version: "1.0.0"
  environment: "development" # production
  debug: true
# nacos配置
nacos:
  host: '1.14.93.5'
  port: 8848
  namespace: '31c727b5-d8a9-421b-9b24-53b565a1091d'
  user: 'nacos'
  password: '152369cj'
  dataId: '.env.development.yaml'
  group: 'Development'