// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\service\careful\system\dept.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	system "github.com/carefuly/careful-admin-go-gin/internal/domain/careful/system"
	system0 "github.com/carefuly/careful-admin-go-gin/internal/service/careful/system"
	gomock "github.com/golang/mock/gomock"
)

// MockDeptService is a mock of DeptService interface.
type MockDeptService struct {
	ctrl     *gomock.Controller
	recorder *MockDeptServiceMockRecorder
}

// MockDeptServiceMockRecorder is the mock recorder for MockDeptService.
type MockDeptServiceMockRecorder struct {
	mock *MockDeptService
}

// NewMockDeptService creates a new mock instance.
func NewMockDeptService(ctrl *gomock.Controller) *MockDeptService {
	mock := &MockDeptService{ctrl: ctrl}
	mock.recorder = &MockDeptServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeptService) EXPECT() *MockDeptServiceMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockDeptService) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockDeptServiceMockRecorder) BatchDelete(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockDeptService)(nil).BatchDelete), ctx, ids)
}

// Create mocks base method.
func (m *MockDeptService) Create(ctx context.Context, domain system.Dept) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeptServiceMockRecorder) Create(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeptService)(nil).Create), ctx, domain)
}

// Delete mocks base method.
func (m *MockDeptService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeptServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeptService)(nil).Delete), ctx, id)
}

// GetById mocks base method.
func (m *MockDeptService) GetById(ctx context.Context, id string) (system.Dept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(system.Dept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockDeptServiceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockDeptService)(nil).GetById), ctx, id)
}

// GetListAll mocks base method.
func (m *MockDeptService) GetListAll(ctx context.Context, filters system.DeptFilter) ([]system.Dept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListAll", ctx, filters)
	ret0, _ := ret[0].([]system.Dept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListAll indicates an expected call of GetListAll.
func (mr *MockDeptServiceMockRecorder) GetListAll(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListAll", reflect.TypeOf((*MockDeptService)(nil).GetListAll), ctx, filters)
}

// GetListTree mocks base method.
func (m *MockDeptService) GetListTree(ctx context.Context, filters system.DeptFilter) ([]system0.DeptTree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListTree", ctx, filters)
	ret0, _ := ret[0].([]system0.DeptTree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListTree indicates an expected call of GetListTree.
func (mr *MockDeptServiceMockRecorder) GetListTree(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListTree", reflect.TypeOf((*MockDeptService)(nil).GetListTree), ctx, filters)
}

// Update mocks base method.
func (m *MockDeptService) Update(ctx context.Context, domain system.Dept) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeptServiceMockRecorder) Update(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeptService)(nil).Update), ctx, domain)
}
