### 登录
POST http://localhost:8080/dev-api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "careful",
  "password": "careful"
}

### 刷新令牌
POST http://localhost:8080/dev-api/v1/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXJlZnVsQOeUqOW_gyIsImF1ZCI6WyJjYXJlZnVsLWFkbWluIl0sImV4cCI6MTc2MDA3OTg4MSwibmJmIjoxNzYwMDc2MjgxLCJpYXQiOjE3NjAwNzYyODEsInVzZXJJZCI6IjAxOTlDODQ1LURGMUEtN0FDNC1BNTAzLUUwNTEzREQ5NDBGOCIsInVzZXJuYW1lIjoiY2FyZWZ1bCIsIkRlcHRJZCI6IjAxOTlDODQzLTk4REMtNzY4Ri05RUNFLTZCM0FGOEU1NTFBOSIsInVzZXJBZ2VudCI6IkludGVsbGlKIEhUVFAgQ2xpZW50L0dvTGFuZCAyMDI0LjMiLCJ1c2VySW5mbyI6eyJkZXB0SWQiOiIwMTk5Qzg0My05OERDLTc2OEYtOUVDRS02QjNBRjhFNTUxQTkiLCJpZCI6IjAxOTlDODQ1LURGMUEtN0FDNC1BNTAzLUUwNTEzREQ5NDBGOCIsInVzZXJuYW1lIjoiY2FyZWZ1bCJ9fQ.X4Dt_aRbfDIsF5aDwGPiyVc3vrMWHfQPwzo_vVRK9UZSTcvB_Ya_8vPcB-T7GyX1bi17oRQvVoKTkw2EVh7NNQ"
}

### 退出登录
POST http://localhost:8080/dev-api/v1/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXJlZnVsQOeUqOW_gyIsImF1ZCI6WyJjYXJlZnVsLWFkbWluIl0sImV4cCI6MTc2MDA4MDI0MywibmJmIjoxNzYwMDc2NjQzLCJpYXQiOjE3NjAwNzY2NDMsInVzZXJJZCI6IjAxOTlDODQ1LURGMUEtN0FDNC1BNTAzLUUwNTEzREQ5NDBGOCIsInVzZXJuYW1lIjoiY2FyZWZ1bCIsIkRlcHRJZCI6IjAxOTlDODQzLTk4REMtNzY4Ri05RUNFLTZCM0FGOEU1NTFBOSIsInVzZXJBZ2VudCI6IkludGVsbGlKIEhUVFAgQ2xpZW50L0dvTGFuZCAyMDI0LjMiLCJ1c2VySW5mbyI6eyJkZXB0SWQiOiIwMTk5Qzg0My05OERDLTc2OEYtOUVDRS02QjNBRjhFNTUxQTkiLCJpZCI6IjAxOTlDODQ1LURGMUEtN0FDNC1BNTAzLUUwNTEzREQ5NDBGOCIsInVzZXJuYW1lIjoiY2FyZWZ1bCJ9fQ.V-GPL6zl3ujUodHXVKznY0R-qYiQPV-ONI0WD3luwAbUV8LZP33wquvagkQ3xUC8rTO9qME892BUmeZHuANqdw

### 获取当前登录用户信息
GET http://localhost:8080/dev-api/v1/auth/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXJlZnVsQOeUqOW_gyIsImF1ZCI6WyJjYXJlZnVsLWFkbWluIl0sImV4cCI6MTc2MDA4MDI0MywibmJmIjoxNzYwMDc2NjQzLCJpYXQiOjE3NjAwNzY2NDMsInVzZXJJZCI6IjAxOTlDODQ1LURGMUEtN0FDNC1BNTAzLUUwNTEzREQ5NDBGOCIsInVzZXJuYW1lIjoiY2FyZWZ1bCIsIkRlcHRJZCI6IjAxOTlDODQzLTk4REMtNzY4Ri05RUNFLTZCM0FGOEU1NTFBOSIsInVzZXJBZ2VudCI6IkludGVsbGlKIEhUVFAgQ2xpZW50L0dvTGFuZCAyMDI0LjMiLCJ1c2VySW5mbyI6eyJkZXB0SWQiOiIwMTk5Qzg0My05OERDLTc2OEYtOUVDRS02QjNBRjhFNTUxQTkiLCJpZCI6IjAxOTlDODQ1LURGMUEtN0FDNC1BNTAzLUUwNTEzREQ5NDBGOCIsInVzZXJuYW1lIjoiY2FyZWZ1bCJ9fQ.V-GPL6zl3ujUodHXVKznY0R-qYiQPV-ONI0WD3luwAbUV8LZP33wquvagkQ3xUC8rTO9qME892BUmeZHuANqdw