// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\repository\repository\careful\system\dept.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	system "github.com/carefuly/careful-admin-go-gin/internal/domain/careful/system"
	gomock "github.com/golang/mock/gomock"
)

// MockDeptRepository is a mock of DeptRepository interface.
type MockDeptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeptRepositoryMockRecorder
}

// MockDeptRepositoryMockRecorder is the mock recorder for MockDeptRepository.
type MockDeptRepositoryMockRecorder struct {
	mock *MockDeptRepository
}

// NewMockDeptRepository creates a new mock instance.
func NewMockDeptRepository(ctrl *gomock.Controller) *MockDeptRepository {
	mock := &MockDeptRepository{ctrl: ctrl}
	mock.recorder = &MockDeptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeptRepository) EXPECT() *MockDeptRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockDeptRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockDeptRepositoryMockRecorder) BatchDelete(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockDeptRepository)(nil).BatchDelete), ctx, ids)
}

// CheckExistByCode mocks base method.
func (m *MockDeptRepository) CheckExistByCode(ctx context.Context, code, excludeId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByCode", ctx, code, excludeId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByCode indicates an expected call of CheckExistByCode.
func (mr *MockDeptRepositoryMockRecorder) CheckExistByCode(ctx, code, excludeId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByCode", reflect.TypeOf((*MockDeptRepository)(nil).CheckExistByCode), ctx, code, excludeId)
}

// CheckExistByNameAndParentId mocks base method.
func (m *MockDeptRepository) CheckExistByNameAndParentId(ctx context.Context, name, parentId, excludeId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByNameAndParentId", ctx, name, parentId, excludeId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByNameAndParentId indicates an expected call of CheckExistByNameAndParentId.
func (mr *MockDeptRepositoryMockRecorder) CheckExistByNameAndParentId(ctx, name, parentId, excludeId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByNameAndParentId", reflect.TypeOf((*MockDeptRepository)(nil).CheckExistByNameAndParentId), ctx, name, parentId, excludeId)
}

// Create mocks base method.
func (m *MockDeptRepository) Create(ctx context.Context, domain system.Dept) (system.Dept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, domain)
	ret0, _ := ret[0].(system.Dept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeptRepositoryMockRecorder) Create(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeptRepository)(nil).Create), ctx, domain)
}

// Delete mocks base method.
func (m *MockDeptRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeptRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeptRepository)(nil).Delete), ctx, id)
}

// GetAncestors mocks base method.
func (m *MockDeptRepository) GetAncestors(ctx context.Context, model system.Dept) ([]system.Dept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAncestors", ctx, model)
	ret0, _ := ret[0].([]system.Dept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAncestors indicates an expected call of GetAncestors.
func (mr *MockDeptRepositoryMockRecorder) GetAncestors(ctx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAncestors", reflect.TypeOf((*MockDeptRepository)(nil).GetAncestors), ctx, model)
}

// GetByCode mocks base method.
func (m *MockDeptRepository) GetByCode(ctx context.Context, code string) (system.Dept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(system.Dept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockDeptRepositoryMockRecorder) GetByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockDeptRepository)(nil).GetByCode), ctx, code)
}

// GetById mocks base method.
func (m *MockDeptRepository) GetById(ctx context.Context, id string) (system.Dept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(system.Dept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockDeptRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockDeptRepository)(nil).GetById), ctx, id)
}

// GetByParentId mocks base method.
func (m *MockDeptRepository) GetByParentId(ctx context.Context, parentId string) (system.Dept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByParentId", ctx, parentId)
	ret0, _ := ret[0].(system.Dept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByParentId indicates an expected call of GetByParentId.
func (mr *MockDeptRepositoryMockRecorder) GetByParentId(ctx, parentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByParentId", reflect.TypeOf((*MockDeptRepository)(nil).GetByParentId), ctx, parentId)
}

// GetChildCount mocks base method.
func (m *MockDeptRepository) GetChildCount(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildCount", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildCount indicates an expected call of GetChildCount.
func (mr *MockDeptRepositoryMockRecorder) GetChildCount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildCount", reflect.TypeOf((*MockDeptRepository)(nil).GetChildCount), ctx, id)
}

// GetListAll mocks base method.
func (m *MockDeptRepository) GetListAll(ctx context.Context, filters system.DeptFilter) ([]system.Dept, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListAll", ctx, filters)
	ret0, _ := ret[0].([]system.Dept)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListAll indicates an expected call of GetListAll.
func (mr *MockDeptRepositoryMockRecorder) GetListAll(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListAll", reflect.TypeOf((*MockDeptRepository)(nil).GetListAll), ctx, filters)
}

// GetUserCount mocks base method.
func (m *MockDeptRepository) GetUserCount(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCount", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCount indicates an expected call of GetUserCount.
func (mr *MockDeptRepositoryMockRecorder) GetUserCount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCount", reflect.TypeOf((*MockDeptRepository)(nil).GetUserCount), ctx, id)
}

// Update mocks base method.
func (m *MockDeptRepository) Update(ctx context.Context, domain system.Dept) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeptRepositoryMockRecorder) Update(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeptRepository)(nil).Update), ctx, domain)
}
