// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\repository\repository\careful\tools\dict_type.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	tools "github.com/carefuly/careful-admin-go-gin/internal/domain/careful/tools"
	gomock "github.com/golang/mock/gomock"
)

// MockDictTypeRepository is a mock of DictTypeRepository interface.
type MockDictTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDictTypeRepositoryMockRecorder
}

// MockDictTypeRepositoryMockRecorder is the mock recorder for MockDictTypeRepository.
type MockDictTypeRepositoryMockRecorder struct {
	mock *MockDictTypeRepository
}

// NewMockDictTypeRepository creates a new mock instance.
func NewMockDictTypeRepository(ctrl *gomock.Controller) *MockDictTypeRepository {
	mock := &MockDictTypeRepository{ctrl: ctrl}
	mock.recorder = &MockDictTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDictTypeRepository) EXPECT() *MockDictTypeRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockDictTypeRepository) BatchDelete(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockDictTypeRepositoryMockRecorder) BatchDelete(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockDictTypeRepository)(nil).BatchDelete), ctx, ids)
}

// Create mocks base method.
func (m *MockDictTypeRepository) Create(ctx context.Context, domain tools.DictType) (tools.DictType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, domain)
	ret0, _ := ret[0].(tools.DictType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDictTypeRepositoryMockRecorder) Create(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDictTypeRepository)(nil).Create), ctx, domain)
}

// Delete mocks base method.
func (m *MockDictTypeRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDictTypeRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDictTypeRepository)(nil).Delete), ctx, id)
}

// GetByDictNames mocks base method.
func (m *MockDictTypeRepository) GetByDictNames(ctx context.Context, dictNames []string) ([]tools.DictType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDictNames", ctx, dictNames)
	ret0, _ := ret[0].([]tools.DictType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDictNames indicates an expected call of GetByDictNames.
func (mr *MockDictTypeRepositoryMockRecorder) GetByDictNames(ctx, dictNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDictNames", reflect.TypeOf((*MockDictTypeRepository)(nil).GetByDictNames), ctx, dictNames)
}

// GetById mocks base method.
func (m *MockDictTypeRepository) GetById(ctx context.Context, id string) (tools.DictType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(tools.DictType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockDictTypeRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockDictTypeRepository)(nil).GetById), ctx, id)
}

// GetListAll mocks base method.
func (m *MockDictTypeRepository) GetListAll(ctx context.Context, filters tools.DictTypeFilter) ([]tools.DictType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListAll", ctx, filters)
	ret0, _ := ret[0].([]tools.DictType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListAll indicates an expected call of GetListAll.
func (mr *MockDictTypeRepositoryMockRecorder) GetListAll(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListAll", reflect.TypeOf((*MockDictTypeRepository)(nil).GetListAll), ctx, filters)
}

// GetListPage mocks base method.
func (m *MockDictTypeRepository) GetListPage(ctx context.Context, filters tools.DictTypeFilter) ([]tools.DictType, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListPage", ctx, filters)
	ret0, _ := ret[0].([]tools.DictType)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetListPage indicates an expected call of GetListPage.
func (mr *MockDictTypeRepositoryMockRecorder) GetListPage(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListPage", reflect.TypeOf((*MockDictTypeRepository)(nil).GetListPage), ctx, filters)
}

// Update mocks base method.
func (m *MockDictTypeRepository) Update(ctx context.Context, domain tools.DictType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDictTypeRepositoryMockRecorder) Update(ctx, domain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDictTypeRepository)(nil).Update), ctx, domain)
}
