// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms",
        "contact": {
            "name": "CJiaの用心 - 技术支持",
            "url": "http://www.swagger.io/support",
            "email": "2224693191@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "description": "账号密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "账号密码登录",
                "parameters": [
                    {
                        "description": "参数信息",
                        "name": "LoginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "用户退出登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取当前登录用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "获取当前登录用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh-token": {
            "post": {
                "description": "使用旧的JWT令牌获取新的令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌参数",
                        "name": "RefreshTokenRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/batchDelete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "批量删除部门信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "批量删除部门",
                "parameters": [
                    {
                        "description": "id数组",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "创建部门信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "创建部门",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "CreateDeptRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.CreateDeptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "删除指定id部门信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "删除部门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/getById/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取指定id部门信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "获取部门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.Dept"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "导入部门信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "导入部门",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件(支持xlsx/csv格式)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/listAll": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取所有部门列表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "获取所有部门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部门名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部门编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部门类型",
                        "name": "dept_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "层级深度",
                        "name": "level",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.Dept"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/listTree": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取部门树形结构信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "获取部门树形结构",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部门名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部门编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "部门类型",
                        "name": "dept_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "层级深度",
                        "name": "level",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.DeptTree"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/dept/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "更新部门信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/部门管理"
                ],
                "summary": "更新部门",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "UpdateDeptRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.UpdateDeptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/batchDelete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "批量删除岗位信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "批量删除岗位",
                "parameters": [
                    {
                        "description": "id数组",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "创建岗位信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "创建岗位",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "CreatePostRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "删除指定id岗位信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "删除岗位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "导出岗位数据到Excel文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "导出岗位数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "岗位名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "岗位编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "岗位类型",
                        "name": "post_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "岗位级别",
                        "name": "level",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所属部门ID",
                        "name": "dept_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Excel文件",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/getById/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取指定id岗位信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "获取岗位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.Post"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "导入岗位信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "导入岗位",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件(支持xlsx/csv格式)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/listAll": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取所有岗位列表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "获取所有岗位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "岗位名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "岗位编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "岗位类型",
                        "name": "post_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "岗位级别",
                        "name": "level",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所属部门ID",
                        "name": "dept_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.Post"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/listPage": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取岗位分页列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "获取岗位分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "岗位名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "岗位编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "岗位类型",
                        "name": "post_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "岗位级别",
                        "name": "level",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "所属部门ID",
                        "name": "dept_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.PostListPageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/post/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "更新岗位信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理/岗位管理"
                ],
                "summary": "更新岗位",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "UpdatePostRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.UpdatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "expire": {
                    "description": "过期时间(秒)",
                    "type": "integer"
                },
                "token": {
                    "description": "JWT令牌",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User"
                        }
                    ]
                }
            }
        },
        "auth.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "description": "旧的JWT令牌",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp..."
                }
            }
        },
        "dept.Type": {
            "type": "string",
            "enum": [
                "company",
                "department",
                "team",
                "other"
            ],
            "x-enum-comments": {
                "TypeCompany": "公司",
                "TypeDepartment": "部门",
                "TypeOther": "其他",
                "TypeTeam": "小组"
            },
            "x-enum-varnames": [
                "TypeCompany",
                "TypeDepartment",
                "TypeTeam",
                "TypeOther"
            ]
        },
        "github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.Dept": {
            "type": "object",
            "properties": {
                "belong_dept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "code": {
                    "description": "部门编码",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept_type": {
                    "description": "部门类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dept.Type"
                        }
                    ]
                },
                "description": {
                    "description": "部门描述",
                    "type": "string"
                },
                "email": {
                    "description": "部门邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "level": {
                    "description": "关联查询字段",
                    "type": "integer"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string"
                },
                "owner": {
                    "description": "部门负责人",
                    "type": "string"
                },
                "parent": {
                    "description": "父部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Dept"
                        }
                    ]
                },
                "parent_id": {
                    "description": "上级部门",
                    "type": "string"
                },
                "path": {
                    "description": "部门路径，格式：/1/2/3/",
                    "type": "string"
                },
                "phone": {
                    "description": "部门电话",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.Post": {
            "type": "object",
            "properties": {
                "Dept": {
                    "description": "所属部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Dept"
                        }
                    ]
                },
                "belong_dept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "code": {
                    "description": "岗位编码",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept_id": {
                    "description": "所属部门",
                    "type": "string"
                },
                "description": {
                    "description": "岗位描述",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "level": {
                    "description": "岗位级别",
                    "allOf": [
                        {
                            "$ref": "#/definitions/post.Level"
                        }
                    ]
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "岗位名称",
                    "type": "string"
                },
                "post_type": {
                    "description": "岗位类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/post.Type"
                        }
                    ]
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "users": {
                    "description": "Post -\u003e User",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.User"
                    }
                }
            }
        },
        "github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "详细地址",
                    "type": "string"
                },
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "belong_dept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "bio": {
                    "description": "个人简介",
                    "type": "string"
                },
                "birthday": {
                    "description": "生日",
                    "type": "string"
                },
                "city": {
                    "description": "所在城市",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept": {
                    "description": "部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Dept"
                        }
                    ]
                },
                "dept_id": {
                    "description": "部门ID",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.GenderConst"
                        }
                    ]
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "is_superuser": {
                    "description": "是否为超级管理员",
                    "type": "boolean"
                },
                "last_login": {
                    "description": "最后登录时间",
                    "type": "string"
                },
                "last_login_ip": {
                    "description": "最后登录IP",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "真实姓名",
                    "type": "string"
                },
                "posts": {
                    "description": "User -\u003e Post",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Post"
                    }
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.Status"
                        }
                    ]
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Dept": {
            "type": "object",
            "properties": {
                "belong_dept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "code": {
                    "description": "部门编码",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept_type": {
                    "description": "部门类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dept.Type"
                        }
                    ]
                },
                "description": {
                    "description": "部门描述",
                    "type": "string"
                },
                "email": {
                    "description": "部门邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "level": {
                    "description": "关联查询字段",
                    "type": "integer"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string"
                },
                "owner": {
                    "description": "部门负责人",
                    "type": "string"
                },
                "parent": {
                    "description": "父部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Dept"
                        }
                    ]
                },
                "parent_id": {
                    "description": "上级部门",
                    "type": "string"
                },
                "path": {
                    "description": "部门路径，格式：/1/2/3/",
                    "type": "string"
                },
                "phone": {
                    "description": "部门电话",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                }
            }
        },
        "github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Post": {
            "type": "object",
            "properties": {
                "Dept": {
                    "description": "所属部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Dept"
                        }
                    ]
                },
                "belong_dept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "code": {
                    "description": "岗位编码",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept_id": {
                    "description": "所属部门",
                    "type": "string"
                },
                "description": {
                    "description": "岗位描述",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "level": {
                    "description": "岗位级别",
                    "allOf": [
                        {
                            "$ref": "#/definitions/post.Level"
                        }
                    ]
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "岗位名称",
                    "type": "string"
                },
                "post_type": {
                    "description": "岗位类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/post.Type"
                        }
                    ]
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "users": {
                    "description": "Post -\u003e User",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.User"
                    }
                }
            }
        },
        "github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.User": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "详细地址",
                    "type": "string"
                },
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "belong_dept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "bio": {
                    "description": "个人简介",
                    "type": "string"
                },
                "birthday": {
                    "description": "生日",
                    "type": "string"
                },
                "city": {
                    "description": "所在城市",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept": {
                    "description": "部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Dept"
                        }
                    ]
                },
                "dept_id": {
                    "description": "部门ID",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.GenderConst"
                        }
                    ]
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "is_superuser": {
                    "description": "是否为超级管理员",
                    "type": "boolean"
                },
                "last_login": {
                    "description": "最后登录时间",
                    "type": "string"
                },
                "last_login_ip": {
                    "description": "最后登录IP",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "真实姓名",
                    "type": "string"
                },
                "posts": {
                    "description": "User -\u003e Post",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Post"
                    }
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.Status"
                        }
                    ]
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "post.Level": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-comments": {
                "LevelGeneralStaff": "一般员工",
                "LevelGrassroots": "基层",
                "LevelHigh": "高层",
                "LevelMiddleLayer": "中层"
            },
            "x-enum-varnames": [
                "LevelHigh",
                "LevelMiddleLayer",
                "LevelGrassroots",
                "LevelGeneralStaff"
            ]
        },
        "post.Type": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-comments": {
                "TypeBusiness": "业务岗",
                "TypeFunctional": "职能岗",
                "TypeManagement": "管理岗",
                "TypeOther": "其他",
                "TypeTechnology": "技术岗"
            },
            "x-enum-varnames": [
                "TypeManagement",
                "TypeTechnology",
                "TypeBusiness",
                "TypeFunctional",
                "TypeOther"
            ]
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "提示信息"
                },
                "request_id": {
                    "description": "请求ID",
                    "type": "string"
                },
                "status": {
                    "description": "响应状态: success|error",
                    "type": "string"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "string"
                }
            }
        },
        "system.CreateDeptRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "部门编码",
                    "type": "string",
                    "maxLength": 50
                },
                "dept_type": {
                    "description": "部门类型",
                    "default": "department",
                    "maxLength": 20,
                    "allOf": [
                        {
                            "$ref": "#/definitions/dept.Type"
                        }
                    ]
                },
                "description": {
                    "description": "部门描述",
                    "type": "string"
                },
                "email": {
                    "description": "部门邮箱",
                    "type": "string",
                    "maxLength": 64
                },
                "name": {
                    "description": "部门名称",
                    "type": "string",
                    "maxLength": 50
                },
                "owner": {
                    "description": "部门负责人",
                    "type": "string",
                    "maxLength": 64
                },
                "parent_id": {
                    "description": "父部门ID",
                    "type": "string",
                    "maxLength": 110
                },
                "phone": {
                    "description": "部门电话",
                    "type": "string",
                    "maxLength": 64
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "default": 1
                },
                "status": {
                    "description": "状态【true-启用 false-停用】",
                    "type": "boolean",
                    "default": true
                }
            }
        },
        "system.CreatePostRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "岗位名称",
                    "type": "string",
                    "maxLength": 50
                },
                "dept_id": {
                    "description": "所属部门ID",
                    "type": "string",
                    "maxLength": 110
                },
                "description": {
                    "description": "岗位描述",
                    "type": "string"
                },
                "level": {
                    "description": "岗位级别",
                    "default": 4,
                    "allOf": [
                        {
                            "$ref": "#/definitions/post.Level"
                        }
                    ]
                },
                "name": {
                    "description": "岗位名称",
                    "type": "string",
                    "maxLength": 50
                },
                "post_type": {
                    "description": "岗位类型",
                    "default": 5,
                    "allOf": [
                        {
                            "$ref": "#/definitions/post.Type"
                        }
                    ]
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "default": 1
                },
                "status": {
                    "description": "状态【true-启用 false-停用】",
                    "type": "boolean",
                    "default": true
                }
            }
        },
        "system.DeptTree": {
            "type": "object",
            "properties": {
                "belong_dept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "children": {
                    "description": "子部门列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/system.DeptTree"
                    }
                },
                "code": {
                    "description": "部门编码",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept_type": {
                    "description": "部门类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dept.Type"
                        }
                    ]
                },
                "description": {
                    "description": "部门描述",
                    "type": "string"
                },
                "email": {
                    "description": "部门邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "level": {
                    "description": "关联查询字段",
                    "type": "integer"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string"
                },
                "owner": {
                    "description": "部门负责人",
                    "type": "string"
                },
                "parent": {
                    "description": "父部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_model_careful_system.Dept"
                        }
                    ]
                },
                "parent_id": {
                    "description": "上级部门",
                    "type": "string"
                },
                "path": {
                    "description": "部门路径，格式：/1/2/3/",
                    "type": "string"
                },
                "phone": {
                    "description": "部门电话",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "system.PostListPageResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.Post"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数量",
                    "type": "integer"
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "system.UpdateDeptRequest": {
            "type": "object",
            "required": [
                "code",
                "id",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "部门编码",
                    "type": "string",
                    "maxLength": 50
                },
                "dept_type": {
                    "description": "部门类型",
                    "default": "department",
                    "maxLength": 20,
                    "allOf": [
                        {
                            "$ref": "#/definitions/dept.Type"
                        }
                    ]
                },
                "description": {
                    "description": "部门描述",
                    "type": "string"
                },
                "email": {
                    "description": "部门邮箱",
                    "type": "string",
                    "maxLength": 64
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string",
                    "maxLength": 50
                },
                "owner": {
                    "description": "部门负责人",
                    "type": "string",
                    "maxLength": 64
                },
                "parent_id": {
                    "description": "父部门ID",
                    "type": "string",
                    "maxLength": 110
                },
                "phone": {
                    "description": "部门电话",
                    "type": "string",
                    "maxLength": 64
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "default": 1
                },
                "status": {
                    "description": "状态【true-启用 false-停用】",
                    "type": "boolean",
                    "default": true
                },
                "timestamp": {
                    "description": "版本",
                    "type": "integer"
                }
            }
        },
        "system.UpdatePostRequest": {
            "type": "object",
            "required": [
                "code",
                "id",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "岗位名称",
                    "type": "string",
                    "maxLength": 50
                },
                "dept_id": {
                    "description": "所属部门ID",
                    "type": "string",
                    "maxLength": 110
                },
                "description": {
                    "description": "岗位描述",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "level": {
                    "description": "岗位级别",
                    "default": 4,
                    "allOf": [
                        {
                            "$ref": "#/definitions/post.Level"
                        }
                    ]
                },
                "name": {
                    "description": "岗位名称",
                    "type": "string",
                    "maxLength": 50
                },
                "post_type": {
                    "description": "岗位类型",
                    "default": 5,
                    "allOf": [
                        {
                            "$ref": "#/definitions/post.Type"
                        }
                    ]
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "default": 1
                },
                "status": {
                    "description": "状态【true-启用 false-停用】",
                    "type": "boolean",
                    "default": true
                },
                "timestamp": {
                    "description": "版本",
                    "type": "integer"
                }
            }
        },
        "user.GenderConst": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "GenderConstFemale": "女",
                "GenderConstMale": "男",
                "GenderConstSecret": "保密"
            },
            "x-enum-varnames": [
                "GenderConstMale",
                "GenderConstFemale",
                "GenderConstSecret"
            ]
        },
        "user.Status": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "StatusDisabled": "禁用",
                "StatusLocked": "锁定",
                "StatusNormal": "正常"
            },
            "x-enum-varnames": [
                "StatusNormal",
                "StatusDisabled",
                "StatusLocked"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT认证令牌，格式: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "开源代码库",
        "url": "https://github.com/carefuly/careful-admin-go-gin"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "CarefulAdmin 后台管理系统 API",
	Description:      "CarefulAdmin 是一个高效、安全的企业级后台管理系统，提供完整的权限管理和数据可视化功能。\n功能模块包括: 用户管理、角色管理、部门管理、菜单管理、操作日志和数据字典等。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
