// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms",
        "contact": {
            "name": "CJiaの用心 - 技术支持",
            "url": "http://www.swagger.io/support",
            "email": "2224693191@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "description": "账号密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "账号密码登录",
                "parameters": [
                    {
                        "description": "参数信息",
                        "name": "LoginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "用户退出登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取当前登录用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "获取当前登录用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/auth/refresh-token": {
            "post": {
                "description": "使用旧的JWT令牌获取新的令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证管理"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌参数",
                        "name": "RefreshTokenRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/create": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "创建字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "创建字典",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "CreateDictRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tools.CreateDictRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/delete/batchDelete": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "批量删除字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "批量删除字典",
                "parameters": [
                    {
                        "description": "id数组",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "删除指定id字典",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "删除字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/export": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "导出字典数据到Excel文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "导出字典数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "字典分类",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "字典值类型",
                        "name": "valueType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Excel文件",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/getById/{id}": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取指定id字典信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "获取字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_tools.Dict"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/import": {
            "post": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "导入字典",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "导入字典",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件(支持xlsx/csv格式)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/listAll": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取所有字典列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "获取所有字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "字典分类",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "字典值类型",
                        "name": "valueType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_tools.Dict"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/listPage": {
            "get": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "获取字典分页列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "获取字典分页列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "修改人",
                        "name": "modifier",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "字典编码",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "字典分类",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "字典值类型",
                        "name": "valueType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tools.DictListPageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/tools/dict/update": {
            "put": {
                "security": [
                    {
                        "LoginToken": []
                    }
                ],
                "description": "更新字典信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统工具/字典管理"
                ],
                "summary": "更新字典",
                "parameters": [
                    {
                        "description": "请求",
                        "name": "UpdateDictRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tools.UpdateDictRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 6
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "auth.LoginResponse": {
            "type": "object",
            "properties": {
                "expire": {
                    "description": "过期时间(秒)",
                    "type": "integer"
                },
                "token": {
                    "description": "JWT令牌",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User"
                        }
                    ]
                }
            }
        },
        "auth.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "description": "旧的JWT令牌",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp..."
                }
            }
        },
        "dict.TypeConst": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "TypeConstEnum": "枚举字典",
                "TypeConstOrdinary": "普通字典",
                "TypeConstSystem": "系统字典"
            },
            "x-enum-varnames": [
                "TypeConstOrdinary",
                "TypeConstSystem",
                "TypeConstEnum"
            ]
        },
        "dict.ValueTypeConst": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "ValueTypeConstBool": "布尔",
                "ValueTypeConstInt": "整型",
                "ValueTypeConstStr": "字符串"
            },
            "x-enum-varnames": [
                "ValueTypeConstStr",
                "ValueTypeConstInt",
                "ValueTypeConstBool"
            ]
        },
        "github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "belongDept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "dept": {
                    "description": "部门",
                    "allOf": [
                        {
                            "$ref": "#/definitions/system.Dept"
                        }
                    ]
                },
                "dept_id": {
                    "description": "部门ID",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.GenderConst"
                        }
                    ]
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "mobile": {
                    "description": "电话",
                    "type": "string"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "github_com_carefuly_careful-admin-go-gin_internal_domain_careful_tools.Dict": {
            "type": "object",
            "properties": {
                "belongDept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "code": {
                    "description": "字典编码",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "字典名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "type": {
                    "description": "字典类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dict.TypeConst"
                        }
                    ]
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "valueType": {
                    "description": "数据类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dict.ValueTypeConst"
                        }
                    ]
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "提示信息"
                },
                "request_id": {
                    "description": "请求ID",
                    "type": "string"
                },
                "status": {
                    "description": "响应状态: success|error",
                    "type": "string"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "string"
                }
            }
        },
        "system.Dept": {
            "type": "object",
            "properties": {
                "belongDept": {
                    "description": "数据归属部门",
                    "type": "string"
                },
                "child_count": {
                    "description": "子部门数量",
                    "type": "integer"
                },
                "children": {
                    "description": "关联查询字段（不存储到数据库）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/system.Dept"
                    }
                },
                "code": {
                    "description": "部门编码",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID(自增)",
                    "type": "string"
                },
                "level": {
                    "description": "层级深度，根节点为0",
                    "type": "integer"
                },
                "modifier": {
                    "description": "修改人",
                    "type": "string"
                },
                "name": {
                    "description": "部门名称",
                    "type": "string"
                },
                "owner": {
                    "description": "负责人",
                    "type": "string"
                },
                "parent": {
                    "description": "父部门信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/system.Dept"
                        }
                    ]
                },
                "parent_id": {
                    "description": "上级部门ID",
                    "type": "string"
                },
                "path": {
                    "description": "节点路径，格式：/1/2/3/\"",
                    "type": "string"
                },
                "phone": {
                    "description": "联系电话",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "显示排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "timestamp": {
                    "description": "版本号(时间戳)",
                    "type": "integer"
                },
                "user_count": {
                    "description": "用户数量",
                    "type": "integer"
                }
            }
        },
        "tools.CreateDictRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "description": "字典编码",
                    "type": "string",
                    "maxLength": 100
                },
                "name": {
                    "description": "字典名称",
                    "type": "string",
                    "maxLength": 100
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "default": 1
                },
                "status": {
                    "description": "状态【true-启用 false-停用】",
                    "type": "boolean",
                    "default": true
                },
                "type": {
                    "description": "字典分类",
                    "default": 1,
                    "allOf": [
                        {
                            "$ref": "#/definitions/dict.TypeConst"
                        }
                    ]
                },
                "valueType": {
                    "description": "字典值类型",
                    "default": 1,
                    "allOf": [
                        {
                            "$ref": "#/definitions/dict.ValueTypeConst"
                        }
                    ]
                }
            }
        },
        "tools.DictListPageResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_tools.Dict"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数量",
                    "type": "integer"
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "tools.UpdateDictRequest": {
            "type": "object",
            "required": [
                "code",
                "id"
            ],
            "properties": {
                "code": {
                    "description": "字典编码",
                    "type": "string",
                    "maxLength": 100
                },
                "id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "maxLength": 255
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "default": 1
                },
                "status": {
                    "description": "状态【true-启用 false-停用】",
                    "type": "boolean",
                    "default": true
                },
                "timestamp": {
                    "description": "版本",
                    "type": "integer"
                }
            }
        },
        "user.GenderConst": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "GenderConstFemale": "女",
                "GenderConstMale": "男",
                "GenderConstSecret": "保密"
            },
            "x-enum-varnames": [
                "GenderConstMale",
                "GenderConstFemale",
                "GenderConstSecret"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT认证令牌，格式: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "开源代码库",
        "url": "https://github.com/carefuly/carefuly-admin-go-gin"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/dev-api",
	Schemes:          []string{"http"},
	Title:            "CarefulAdmin 后台管理系统 API",
	Description:      "CarefulAdmin 是一个高效、安全的企业级后台管理系统，提供完整的权限管理和数据可视化功能。\n功能模块包括: 用户管理、角色管理、部门管理、菜单管理、操作日志和数据字典等。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
