basePath: /dev-api
definitions:
  auth.LoginRequest:
    properties:
      password:
        description: 密码
        maxLength: 50
        minLength: 6
        type: string
      username:
        description: 用户名
        maxLength: 50
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  auth.LoginResponse:
    properties:
      expire:
        description: 过期时间(秒)
        type: integer
      token:
        description: JWT令牌
        type: string
      user:
        allOf:
        - $ref: '#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User'
        description: 用户信息
    type: object
  auth.RefreshTokenRequest:
    properties:
      token:
        description: 旧的JWT令牌
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp...
        type: string
    required:
    - token
    type: object
  dict.TypeConst:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-comments:
      TypeConstEnum: 枚举字典
      TypeConstOrdinary: 普通字典
      TypeConstSystem: 系统字典
    x-enum-varnames:
    - TypeConstOrdinary
    - TypeConstSystem
    - TypeConstEnum
  dict.ValueTypeConst:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-comments:
      ValueTypeConstBool: 布尔
      ValueTypeConstInt: 整型
      ValueTypeConstStr: 字符串
    x-enum-varnames:
    - ValueTypeConstStr
    - ValueTypeConstInt
    - ValueTypeConstBool
  github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User:
    properties:
      avatar:
        description: 头像
        type: string
      belongDept:
        description: 数据归属部门
        type: string
      createTime:
        description: 创建时间
        type: string
      creator:
        description: 创建人
        type: string
      dept:
        allOf:
        - $ref: '#/definitions/system.Dept'
        description: 部门
      dept_id:
        description: 部门ID
        type: string
      email:
        description: 邮箱
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/user.GenderConst'
        description: 性别
      id:
        description: 主键ID(自增)
        type: string
      mobile:
        description: 电话
        type: string
      modifier:
        description: 修改人
        type: string
      name:
        description: 姓名
        type: string
      remark:
        description: 备注
        type: string
      sort:
        description: 显示排序
        type: integer
      status:
        description: 状态
        type: boolean
      timestamp:
        description: 版本号(时间戳)
        type: integer
      updateTime:
        description: 更新时间
        type: string
      username:
        description: 用户名
        type: string
    type: object
  github_com_carefuly_careful-admin-go-gin_internal_domain_careful_tools.Dict:
    properties:
      belongDept:
        description: 数据归属部门
        type: string
      code:
        description: 字典编码
        type: string
      createTime:
        description: 创建时间
        type: string
      creator:
        description: 创建人
        type: string
      id:
        description: 主键ID(自增)
        type: string
      modifier:
        description: 修改人
        type: string
      name:
        description: 字典名称
        type: string
      remark:
        description: 备注
        type: string
      sort:
        description: 显示排序
        type: integer
      status:
        description: 状态
        type: boolean
      timestamp:
        description: 版本号(时间戳)
        type: integer
      type:
        allOf:
        - $ref: '#/definitions/dict.TypeConst'
        description: 字典类型
      updateTime:
        description: 更新时间
        type: string
      valueType:
        allOf:
        - $ref: '#/definitions/dict.ValueTypeConst'
        description: 数据类型
    type: object
  response.Response:
    properties:
      code:
        description: HTTP状态码
        type: integer
      data:
        description: 数据
      msg:
        description: 提示信息
      request_id:
        description: 请求ID
        type: string
      status:
        description: '响应状态: success|error'
        type: string
      timestamp:
        description: 时间戳
        type: string
    type: object
  system.Dept:
    properties:
      belongDept:
        description: 数据归属部门
        type: string
      child_count:
        description: 子部门数量
        type: integer
      children:
        description: 关联查询字段（不存储到数据库）
        items:
          $ref: '#/definitions/system.Dept'
        type: array
      code:
        description: 部门编码
        type: string
      creator:
        description: 创建人
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: 主键ID(自增)
        type: string
      level:
        description: 层级深度，根节点为0
        type: integer
      modifier:
        description: 修改人
        type: string
      name:
        description: 部门名称
        type: string
      owner:
        description: 负责人
        type: string
      parent:
        allOf:
        - $ref: '#/definitions/system.Dept'
        description: 父部门信息
      parent_id:
        description: 上级部门ID
        type: string
      path:
        description: 节点路径，格式：/1/2/3/"
        type: string
      phone:
        description: 联系电话
        type: string
      remark:
        description: 备注
        type: string
      sort:
        description: 显示排序
        type: integer
      status:
        description: 状态
        type: boolean
      timestamp:
        description: 版本号(时间戳)
        type: integer
      user_count:
        description: 用户数量
        type: integer
    type: object
  tools.CreateDictRequest:
    properties:
      code:
        description: 字典编码
        maxLength: 100
        type: string
      name:
        description: 字典名称
        maxLength: 100
        type: string
      remark:
        description: 备注
        maxLength: 255
        type: string
      sort:
        default: 1
        description: 排序
        type: integer
      status:
        default: true
        description: 状态【true-启用 false-停用】
        type: boolean
      type:
        allOf:
        - $ref: '#/definitions/dict.TypeConst'
        default: 1
        description: 字典分类
      valueType:
        allOf:
        - $ref: '#/definitions/dict.ValueTypeConst'
        default: 1
        description: 字典值类型
    required:
    - code
    - name
    type: object
  tools.DictListPageResponse:
    properties:
      list:
        description: 列表
        items:
          $ref: '#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_tools.Dict'
        type: array
      page:
        description: 页码
        type: integer
      pageSize:
        description: 每页数量
        type: integer
      total:
        description: 总数
        type: integer
    type: object
  tools.UpdateDictRequest:
    properties:
      code:
        description: 字典编码
        maxLength: 100
        type: string
      id:
        description: 主键ID
        type: string
      remark:
        description: 备注
        maxLength: 255
        type: string
      sort:
        default: 1
        description: 排序
        type: integer
      status:
        default: true
        description: 状态【true-启用 false-停用】
        type: boolean
      timestamp:
        description: 版本
        type: integer
    required:
    - code
    - id
    type: object
  user.GenderConst:
    enum:
    - 1
    - 2
    - 3
    type: integer
    x-enum-comments:
      GenderConstFemale: 女
      GenderConstMale: 男
      GenderConstSecret: 保密
    x-enum-varnames:
    - GenderConstMale
    - GenderConstFemale
    - GenderConstSecret
externalDocs:
  description: 开源代码库
  url: https://github.com/carefuly/carefuly-admin-go-gin
host: localhost:8080
info:
  contact:
    email: 2224693191@qq.com
    name: CJiaの用心 - 技术支持
    url: http://www.swagger.io/support
  description: |-
    CarefulAdmin 是一个高效、安全的企业级后台管理系统，提供完整的权限管理和数据可视化功能。
    功能模块包括: 用户管理、角色管理、部门管理、菜单管理、操作日志和数据字典等。
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms
  title: CarefulAdmin 后台管理系统 API
  version: 1.0.0
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: 账号密码登录
      parameters:
      - description: 参数信息
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: 账号密码登录
      tags:
      - 认证管理
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      description: 用户退出登录
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      - LoginToken: []
      summary: 退出登录
      tags:
      - 认证管理
  /v1/auth/profile:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_system.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      - LoginToken: []
      summary: 获取当前登录用户信息
      tags:
      - 认证管理
  /v1/auth/refresh-token:
    post:
      consumes:
      - application/json
      description: 使用旧的JWT令牌获取新的令牌
      parameters:
      - description: 刷新令牌参数
        in: body
        name: RefreshTokenRequest
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Response'
      summary: 刷新令牌
      tags:
      - 认证管理
  /v1/tools/dict/create:
    post:
      consumes:
      - application/json
      description: 创建字典
      parameters:
      - description: 请求
        in: body
        name: CreateDictRequest
        required: true
        schema:
          $ref: '#/definitions/tools.CreateDictRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 创建字典
      tags:
      - 系统工具/字典管理
  /v1/tools/dict/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 删除指定id字典
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 删除字典
      tags:
      - 系统工具/字典管理
  /v1/tools/dict/delete/batchDelete:
    post:
      consumes:
      - application/json
      description: 批量删除字典
      parameters:
      - description: id数组
        in: body
        name: ids
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 批量删除字典
      tags:
      - 系统工具/字典管理
  /v1/tools/dict/export:
    get:
      consumes:
      - application/json
      description: 导出字典数据到Excel文件
      parameters:
      - description: 创建人
        in: query
        name: creator
        type: string
      - description: 修改人
        in: query
        name: modifier
        type: string
      - default: true
        description: 状态
        in: query
        name: status
        type: boolean
      - description: 字典名称
        in: query
        name: name
        type: string
      - description: 字典编码
        in: query
        name: code
        type: string
      - default: 1
        description: 字典分类
        in: query
        name: type
        required: true
        type: integer
      - default: 1
        description: 字典值类型
        in: query
        name: valueType
        required: true
        type: integer
      produces:
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      responses:
        "200":
          description: Excel文件
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 导出字典数据
      tags:
      - 系统工具/字典管理
  /v1/tools/dict/getById/{id}:
    get:
      consumes:
      - application/json
      description: 获取指定id字典信息
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_tools.Dict'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 获取字典
      tags:
      - 系统工具/字典管理
  /v1/tools/dict/import:
    post:
      consumes:
      - multipart/form-data
      description: 导入字典
      parameters:
      - description: 文件(支持xlsx/csv格式)
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 导入字典
      tags:
      - 系统工具/字典管理
  /v1/tools/dict/listAll:
    get:
      consumes:
      - application/json
      description: 获取所有字典列表
      parameters:
      - description: 创建人
        in: query
        name: creator
        type: string
      - description: 修改人
        in: query
        name: modifier
        type: string
      - default: true
        description: 状态
        in: query
        name: status
        type: boolean
      - description: 字典名称
        in: query
        name: name
        type: string
      - description: 字典编码
        in: query
        name: code
        type: string
      - default: 0
        description: 字典分类
        in: query
        name: type
        required: true
        type: integer
      - default: 0
        description: 字典值类型
        in: query
        name: valueType
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/github_com_carefuly_careful-admin-go-gin_internal_domain_careful_tools.Dict'
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 获取所有字典
      tags:
      - 系统工具/字典管理
  /v1/tools/dict/listPage:
    get:
      consumes:
      - application/json
      description: 获取字典分页列表
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 创建人
        in: query
        name: creator
        type: string
      - description: 修改人
        in: query
        name: modifier
        type: string
      - default: true
        description: 状态
        in: query
        name: status
        type: boolean
      - description: 字典名称
        in: query
        name: name
        type: string
      - description: 字典编码
        in: query
        name: code
        type: string
      - default: 0
        description: 字典分类
        in: query
        name: type
        required: true
        type: integer
      - default: 0
        description: 字典值类型
        in: query
        name: valueType
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.DictListPageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 获取字典分页列表
      tags:
      - 系统工具/字典管理
  /v1/tools/dict/update:
    put:
      consumes:
      - application/json
      description: 更新字典信息
      parameters:
      - description: 请求
        in: body
        name: UpdateDictRequest
        required: true
        schema:
          $ref: '#/definitions/tools.UpdateDictRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - LoginToken: []
      summary: 更新字典
      tags:
      - 系统工具/字典管理
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: 'JWT认证令牌，格式: "Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
